M48
; DRILL file {KiCad 8.0.4} date 2024-12-04T08:51:36-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-04T08:51:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0430
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1260
%
G90
G05
T1
X4.1693Y-2.3189
X4.1693Y-2.5465
T2
X4.1201Y-2.0295
X4.2972Y-2.0295
T3
X4.7205Y-3.2795
T4
X4.7205Y-2.4921
T5
X4.487Y-3.837
X4.537Y-1.937
X6.537Y-2.537
X6.537Y-3.637
M30
